### ISSUE TITLE
Consider relicensing to LGPL or MIT

### ISSUE THREAD

**Issue by GeorgesStavracas** [flatpak/libportal#36]
So that proprietary applications can link libportal and use all the goodness of this fantastic platform.

This will require explicit approval from:

 * ✔ @GeorgesStavracas 
 * ✔ @grulja 
 * ✔ @hadess 
 * ✔@jtojnar 
 * ✔@matthiasclasen 
 * ✔@mjog
 * ✔ @smcv 
 * ✔ @TingPing

**Comment by TingPing** [comment]
I approve of relicensing my work to any LGPL version or MIT.

**Comment by TingPing** [comment]
Glancing at a few files they have the lgpl header.

**Comment by GeorgesStavracas** [comment]
The COPYING file in this repository is GPLv2 though.

**Comment by smcv** [comment]
I approve relicensing my work on libportal to any LGPL version or MIT.

**Comment by jtojnar** [comment]
I approve of relicensing my work to any LGPL version or MIT.

**Comment by grulja** [comment]
I approve relicensing my work on libportal to any LGPL version or MIT.

**Comment by matthiasclasen** [comment]
Fine with me too, as I already said on irc.

**Comment by mjog** [comment]
Sorry to be /that guy/, but what's the use case? IIRC FSF guidelines state LGPL should be used when there is an an incumbent proprietary equivalent, otherwise use the GPL. That's not clear to me here?

**Comment by GeorgesStavracas** [comment]
Some proprietary apps (say, [clears throad] *merely for example*, Zoom) might want to use libportal in the future to implement Wayland-compatible screencapture, or webcam capture using portals without having to deal with the D-Bus complexity that comes with it.

**Comment by smcv** [comment]
The way I see it is that the choice of strong copyleft vs. weak copyleft vs. permissive is situational and tactical: which will improve the world more, using the project you're licensing as a lever to encourage/require other projects to be Free Software, or having wide adoption of the project?

In the case of libportal, it's an enabler for things we want to make the Linux ecosystem better (more sandboxed apps), so it makes sense to me to license it permissively - weak copyleft (LGPL), or even permissive (MIT) if that's feasible (which mainly depends on whether code was copied into libportal from LGPL projects like GLib). This is basically the same reasoning as things like libpng being permissively-licensed: I suspect Free Software benefitted more from wide adoption of PNG than it would have benefitted from having a compressed image format that only Free Software could consume.

It seems vanishingly unlikely that authors of proprietary apps like Zoom and Steam are going to relicense to GPL in order to use libportal, so having libportal under strong copyleft doesn't seem like it brings significant benefit in terms of expanding the commons.

However, if it's clear to proprietary app authors that they are welcome to use libportal without legal or technical barriers, then at least we can maybe have proprietary apps that work acceptably in a Wayland/sandboxed world, which seems better than having to give those proprietary apps a weaker sandbox than they ought to need (and use X11 rather than Wayland) to have them work on Linux at all?

Of course, in an ideal world, all app authors would be happy to release their app as Free Software, and all app authors would consider it to be a design requirement that their app works well in a Flatpak or similar sandbox - but since we don't live in that ideal world (yet?) and it doesn't seem very likely to happen any time soon, I think it makes sense to try to get incremental improvements.

**Comment by mjog** [comment]
Okay, sounds fair. Thanks both.

I approve of relicensing my work to any LGPL version or MIT, with a preference for LGPL.

**Comment by hadess** [comment]
I'd like to know which *exact* license gets selected before given an answer either way. Is the goal to dual-license? Have all the licenses for existing files been checked?

**Comment by GeorgesStavracas** [comment]
My personal tendency, which seems to resonate with others here, is LGPL. Unless someone comes up with a pretty strong reason to use MIT, I'll open a pull request relicensing libportal to LGPL. No dual-licensing.

**Comment by smcv** [comment]
Every file that contains licensing information seems to be [LGPL-2.0-or-later](https://spdx.org/licenses/LGPL-2.0-or-later.html).

**Comment by hadess** [comment]
I approve for my changes to be relicensed under the GNU LGPL v3 (with the option for later versions being removed, as only the FSF is allowed to release new versions, and we all know what the FSF is like).

> Every file that contains licensing information seems to be [LGPL-2.0-or-later](https://spdx.org/licenses/LGPL-2.0-or-later.html).

You'll probably still want to double-check the source for the rest of the changes.

**Comment by GeorgesStavracas** [comment]
Fantastic, seems like everyone listed agreed with relicensing.

The license that satisfies everyone's constraints is [**LGPL-3.0**](https://spdx.org/licenses/LGPL-3.0.html).

**Comment by hadess** [comment]
> The license that satisfies everyone's constraints is [**LGPL-3.0**](https://spdx.org/licenses/LGPL-3.0.html).

https://spdx.org/licenses/LGPL-3.0-only.html

**Comment by smcv** [comment]
Obviously I'm not a major contributor to this codebase, and I've already given broad permission for relicensing my small contributions, but I feel that I should mention before this is finalized: LGPL-3.0-only is awkward if we ever want to copy/move libportal code into GLib, which is a mixture of LGPL-2.0-or-later and LGPL-2.1-or-later. Under at least some interpretations, this license would also mean GPL-2.0-only apps (e.g. git) can't link to libportal.

Is there a reason we want to be excluding LGPL-2.1? Some vendors are very strongly opposed to the whole GPL 3 family over the "anti-tivoization" clause, and while big projects like gcc might be able to use their licensing as a lever to get GPL 3 more widely accepted, I think the more likely result of libportal having too strong a license is people not using libportal, which seems counterproductive (going back to my earlier comment).

> with the option for later versions being removed, as only the FSF is allowed to release new versions, and we all know what the FSF is like

If you're concerned about the FSF going completely off the rails and issuing new license versions that are objectionable in some way, then one possibility would be to multi-license under `LGPL-2.1-only`, `LGPL-3.0-only`, or versions of the LGPL accepted by a nominated proxy (the GNOME Foundation?) under LGPL-3.0 §6.

Note that the FSF's hands are somewhat tied by their non-profit status (a mission statement is part of the foundation's legal existence), and by the (L)GPL license family promising that new versions are "similar in spirit to the present version", so there's a limit to how badly their license-steward status can go wrong.

**Comment by Newbytee** [comment]
I'm obviously not a contributor here, but I wonder if there is any significant reason to go with LGPL over MIT. [LGPL makes static linking awkward](https://www.gnu.org/licenses/gpl-faq.en.html#LGPLStaticVsDynamic) for proprietary software (and some people really like static linking), and is there any real concern that someone would make a proprietary fork of libportal? Even if someone did, I don't think it would matter much given the limited scope of this library.

**Comment by GeorgesStavracas** [comment]
> I wonder if there is any significant reason to go with LGPL over MIT

I think it's generally a good idea to go with a less proprietary-friendly license whenever possible.

**Comment by falkTX** [comment]
Sorry to bring up this topic again, but for the use case of proprietary software plugins (where we want self-contained builds as much as possible) the LGPL does not really work.
LGPL3-only also seems like an odd choice, it conflicts with any project that wants to maintain a GPLv3+ compatibility intact, it also is not compatible with GPL2-only codebases...

So while I was happy to see that this project exists, it is really not usable yet for stuff like https://github.com/DISTRHO/DPF/ that I maintain. That means needing to keep doing direct dbus calls, basically multiple implementations for the same thing.

Glad to discuss more if you need to understand the detailed reasons for wanting a more liberal license.

**Comment by Newbytee** [comment]
For what it's worth, there is also https://github.com/bilelmoussaoui/ashpd, which is MIT-licenced. But it's written in Rust.

**Comment by TingPing** [comment]
Most authors did approve of MIT, including myself, but not all so here we are unless somebody removes their work.

Though I think "LGPL can't be used because I *must* static link" is a lame excuse. It is pretty easy to ship one extra file.

**Comment by falkTX** [comment]
> Though I think "LGPL can't be used because I _must_ static link" is a lame excuse. It is pretty easy to ship one extra file.

this is not really doable for software plugins, which I mentioned in my post.

stuff like VST3 and CLAP plugins must be self-contained, they can't rely on a libportal existing on the system. and if each plugin carries their own libportal it means many multiple copies of the same shared library all running within the same process (which can be very risky due to ABI/API breakages)

my use-case is not containers, but multiple plugins that all run inside a single application like Ardour, Bitwig or Reaper.

**Comment by TingPing** [comment]
Relicensing again is just even more tricky now that it has been years with more contributors :/
